# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addTypeDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addTypeDialog(object):
    def setupUi(self, addTypeDialog):
        addTypeDialog.setObjectName("addTypeDialog")
        addTypeDialog.resize(402, 169)
        self.warninglbl = QtWidgets.QLabel(addTypeDialog)
        self.warninglbl.setGeometry(QtCore.QRect(150, 55, 201, 16))
        self.warninglbl.setStyleSheet("color: rgb(255, 0, 0);")
        self.warninglbl.setText("")
        self.warninglbl.setObjectName("warninglbl")
        self.titleLine = QtWidgets.QLineEdit(addTypeDialog)
        self.titleLine.setGeometry(QtCore.QRect(150, 20, 231, 31))
        self.titleLine.setObjectName("titleLine")
        self.label_3 = QtWidgets.QLabel(addTypeDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.label_3.setObjectName("label_3")
        self.periodicCheckBox = QtWidgets.QCheckBox(addTypeDialog)
        self.periodicCheckBox.setGeometry(QtCore.QRect(30, 90, 141, 17))
        self.periodicCheckBox.setObjectName("periodicCheckBox")
        self.timeBasedCheckBox = QtWidgets.QCheckBox(addTypeDialog)
        self.timeBasedCheckBox.setGeometry(QtCore.QRect(220, 90, 171, 17))
        self.timeBasedCheckBox.setObjectName("timeBasedCheckBox")
        self.addButton = QtWidgets.QPushButton(addTypeDialog)
        self.addButton.setGeometry(QtCore.QRect(140, 130, 101, 23))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(addTypeDialog)
        QtCore.QMetaObject.connectSlotsByName(addTypeDialog)

    def retranslateUi(self, addTypeDialog):
        _translate = QtCore.QCoreApplication.translate
        addTypeDialog.setWindowTitle(_translate("addTypeDialog", "Добавить тип события"))
        self.label_3.setText(_translate("addTypeDialog", "Название:"))
        self.periodicCheckBox.setText(_translate("addTypeDialog", "Периодичное событие?"))
        self.timeBasedCheckBox.setText(_translate("addTypeDialog", "Требуется к выполнению?"))
        self.addButton.setText(_translate("addTypeDialog", "Добавить"))
