# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 911)
        self.setWindowIcon(QtGui.QIcon('icon.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainCalendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.mainCalendar.setGeometry(QtCore.QRect(0, 0, 831, 621))
        self.mainCalendar.setObjectName("mainCalendar")
        self.dateData = QtWidgets.QWidget(self.centralwidget)
        self.dateData.setGeometry(QtCore.QRect(0, 620, 831, 271))
        self.dateData.setObjectName("dateData")
        self.editButton = QtWidgets.QPushButton(self.dateData)
        self.editButton.setGeometry(QtCore.QRect(380, 0, 181, 31))
        self.editButton.setObjectName("editButton")
        self.delButton = QtWidgets.QPushButton(self.dateData)
        self.delButton.setGeometry(QtCore.QRect(580, 0, 181, 31))
        self.delButton.setObjectName("delButton")
        self.entryTable = QtWidgets.QTableWidget(self.dateData)
        self.entryTable.setGeometry(QtCore.QRect(0, 40, 831, 231))
        self.entryTable.setObjectName("entryTable")
        self.entryTable.setColumnCount(0)
        self.entryTable.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 620, 381, 41))
        self.widget.setObjectName("widget")
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setGeometry(QtCore.QRect(180, 0, 181, 31))
        self.addButton.setObjectName("addButton")
        self.curDate = QtWidgets.QLabel(self.widget)
        self.curDate.setGeometry(QtCore.QRect(10, 7, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.curDate.setFont(font)
        self.curDate.setObjectName("curDate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 839, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.addAction = QtWidgets.QAction(MainWindow)
        self.addAction.setObjectName("addAction")
        self.uselessAction = QtWidgets.QAction(MainWindow)
        self.uselessAction.setObjectName("uselessAction")
        self.calcAction = QtWidgets.QAction(MainWindow)
        self.calcAction.setObjectName("calcAction")
        self.menu.addAction(self.addAction)
        self.menu.addAction(self.uselessAction)
        self.menu.addAction(self.calcAction)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "THE BEST PROJECT OF ALL TIMES AND PEOPLES"))
        self.editButton.setText(_translate("MainWindow", "Редактировать запись"))
        self.delButton.setText(_translate("MainWindow", "Удалить запись"))
        self.addButton.setText(_translate("MainWindow", "Добавить запись"))
        self.curDate.setText(_translate("MainWindow", "CurrentDate"))
        self.menu.setTitle(_translate("MainWindow", "Дополнительно"))
        self.addAction.setText(_translate("MainWindow", "Добавить тип записи"))
        self.uselessAction.setText(_translate("MainWindow", "Открыть заметки"))
        self.calcAction.setText(_translate("MainWindow", "Рассчёт даты"))
